language: node_js
node_js:
  - "5"
before_install: npm install -g grunt-cli
install:
  - npm install
  - bower install
script: grunt test
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

